# Generated by Django 4.1.7 on 2023-03-26 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_mypolygon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
