# Generated by Django 4.1.7 on 2023-03-26 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
