# Generated by Django 4.1.7 on 2023-03-27 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_client_client_id'),
        ('map', '0007_mypolygon_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mypolygon',
            name='author',
        ),
        migrations.AddField(
            model_name='mypolygon',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='signup.client'),
        ),
    ]
