# Generated by Django 4.1.7 on 2023-04-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_client_supervisor_supervisor_supervisor_id'),
        ('map', '0009_mypolygon_supervisor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='myPolygon',
            new_name='mPolygons',
        ),
    ]
