# Generated by Django 4.1.7 on 2023-04-07 20:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_myproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='cityp',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='myproject',
            name='debutp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='myproject',
            name='descp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='myproject',
            name='finp',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='mPolygons',
        ),
    ]
