# Generated by Django 4.1.7 on 2023-04-07 20:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_myproject_cityp_myproject_debutp_myproject_descp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='geomp',
            field=django.contrib.gis.db.models.fields.PolygonField(null=True, srid=4326),
        ),
    ]
