# Generated by Django 4.1.7 on 2023-04-07 21:45

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_alter_myproject_geomp'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='locationp',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
