# Generated by Django 4.1.7 on 2023-04-08 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_myproject_clientp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myproject',
            name='id',
        ),
        migrations.AddField(
            model_name='myproject',
            name='polygon_id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
