# Generated by Django 4.1.7 on 2023-04-12 17:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myproject',
            name='geomp',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True, srid=4326),
        ),
    ]
