# Generated by Django 4.1.7 on 2023-04-13 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_alter_client_nom_alter_client_prenom'),
        ('map', '0018_alter_myproject_geomp'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='supervisorp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='signup.supervisor'),
        ),
    ]
