# Generated by Django 4.1.7 on 2023-04-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_myproject_supervisorp'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='Battery_value',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='FWI',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='RSSI',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='Sensors',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='reference',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
