# Generated by Django 4.1.7 on 2023-04-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_node_battery_value_node_fwi_node_rssi_node_sensors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='id',
        ),
        migrations.AddField(
            model_name='node',
            name='Idnode',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
