# Generated by Django 4.1.7 on 2023-04-15 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0021_remove_node_id_node_idnode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('IdData', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('temperature', models.BigIntegerField(null=True)),
                ('humidity', models.BigIntegerField(null=True)),
                ('wind', models.BigIntegerField(default=0)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datas', to='map.node')),
            ],
        ),
    ]
