# Generated by Django 4.1.7 on 2023-04-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='wind',
            field=models.FloatField(null=True),
        ),
    ]
