# Generated by Django 4.1.7 on 2023-04-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0023_alter_data_wind'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='rain',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='FWI',
            field=models.FloatField(null=True),
        ),
    ]
