# Generated by Django 4.1.7 on 2023-04-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_data_rain_alter_node_fwi'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='range',
            field=models.BigIntegerField(null=True),
        ),
    ]
