# Generated by Django 4.1.7 on 2023-04-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0025_node_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='range',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
