# Generated by Django 4.1.7 on 2023-04-19 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0026_alter_node_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='range',
            new_name='node_range',
        ),
    ]
