# Generated by Django 4.1.7 on 2023-04-19 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0027_rename_range_node_node_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='FWI',
            field=models.BigIntegerField(null=True),
        ),
    ]
