# Generated by Django 4.1.7 on 2023-04-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0028_alter_node_fwi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='rain',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='wind',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
