# Generated by Django 4.1.7 on 2023-04-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0029_alter_data_rain_alter_data_wind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='FWI',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
