# Generated by Django 4.1.7 on 2023-04-29 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0031_parcelle'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelle', to='map.myproject'),
        ),
    ]
