# Generated by Django 4.1.7 on 2023-04-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0032_parcelle_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='namep',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
