# Generated by Django 4.1.7 on 2023-04-29 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0034_alter_parcelle_namep'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='parc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_related', to='map.parcelle'),
        ),
    ]
