# Generated by Django 4.1.7 on 2023-05-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0035_node_parc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='rain',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='wind',
            field=models.FloatField(default=0, null=True),
        ),
    ]
