# Generated by Django 4.1.7 on 2023-05-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0037_alter_node_fwi'),
    ]

    operations = [
        migrations.AddField(
            model_name='myproject',
            name='piece_joinde',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
