# Generated by Django 4.2.1 on 2023-05-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0038_myproject_piece_joinde'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='detection',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
