# Generated by Django 4.2.1 on 2023-06-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0039_node_detection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='detection',
        ),
        migrations.AddField(
            model_name='data',
            name='RSSI',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='detection',
            field=models.BigIntegerField(null=True),
        ),
    ]
