# Generated by Django 4.2.1 on 2023-06-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0041_remove_data_rssi_remove_data_detection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
