# Generated by Django 4.1.7 on 2023-03-27 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_client_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='author',
        ),
    ]
