# Generated by Django 4.1.7 on 2023-05-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_alter_client_nom_alter_client_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
