# Generated by Django 4.1.7 on 2023-05-03 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0008_supervisor_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_id',
        ),
    ]
