# Generated by Django 4.1.7 on 2023-05-09 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_remove_client_client_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='supervisor_id',
        ),
    ]
