# Generated by Django 4.1.7 on 2023-05-17 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0011_supervisor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='user',
        ),
    ]
