# Generated by Django 4.1.7 on 2023-05-18 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0014_alter_supervisor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='supervisor',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
